[package]
name = "ch32-data-gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
glob = "0.3.1"
serde = { version = "1.0.157", features = ["derive"] }
serde_yaml = "0.9.19"
chiptool = { git = "https://github.com/ch32-rs/chiptool", rev = "1c198ae678ebd426751513f0deab6fbd6f8b8211" }
serde_json = "1.0.94"
ch32-data-serde = { version = "0.1.0", path = "../ch32-data-serde" }
pretty_env_logger = "0.5.0"
